import { createHash } from 'node:crypto';

// Exact SQLite object text is part of the on-disk journal format. Never migrate in place.
const U = c => `typeof(${c})='text' AND length(${c})=36 AND ${c} GLOB '[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]'`;
const H = c => `typeof(${c})='text' AND length(${c})=64 AND ${c} NOT GLOB '*[^0-9a-f]*'`;
const N = (c,min=0) => `typeof(${c})='integer' AND ${c} BETWEEN ${min} AND 9007199254740991`;
const B = c => `typeof(${c})='integer' AND ${c} IN (0,1)`;
const J = (c,max) => `json_valid(${c}) AND typeof(${c})='text' AND length(CAST(${c} AS BLOB))<=${max}`;
export const JOURNAL_DDL = Object.freeze({
  im_v2_client_meta: `CREATE TABLE im_v2_client_meta (singleton INTEGER NOT NULL PRIMARY KEY CHECK(singleton=1),version INTEGER NOT NULL CHECK(version=2),checksum TEXT NOT NULL CHECK(${H('checksum')}))`,
  im_v2_client_partitions: `CREATE TABLE im_v2_client_partitions (partition_id TEXT NOT NULL PRIMARY KEY CHECK(${H('partition_id')}),center_origin TEXT NOT NULL CHECK(typeof(center_origin)='text' AND length(CAST(center_origin AS BLOB))<=2048),stable_instance_id TEXT NOT NULL CHECK(${U('stable_instance_id')}),agent_id TEXT NOT NULL CHECK(${U('agent_id')}),center_epoch TEXT NOT NULL CHECK(${U('center_epoch')}),status TEXT NOT NULL CHECK(typeof(status)='text' AND status IN ('active','reconciliation_required','archived')),predecessor_id TEXT CHECK(predecessor_id IS NULL OR (${H('predecessor_id')})) REFERENCES im_v2_client_partitions(partition_id),decision_ref TEXT CHECK(decision_ref IS NULL OR (typeof(decision_ref)='text' AND length(decision_ref) BETWEEN 1 AND 255 AND decision_ref NOT GLOB '*[' || char(1) || '-' || char(31) || char(127) || ']*' AND instr(decision_ref,char(0))=0)),created_at INTEGER NOT NULL CHECK(${N('created_at')}),UNIQUE(center_origin,stable_instance_id,agent_id,center_epoch),CHECK((predecessor_id IS NULL AND decision_ref IS NULL) OR (predecessor_id IS NOT NULL AND decision_ref IS NOT NULL AND predecessor_id<>partition_id)))`,
  im_v2_client_outgoing: `CREATE TABLE im_v2_client_outgoing (partition_id TEXT NOT NULL CHECK(${H('partition_id')}) REFERENCES im_v2_client_partitions(partition_id),origin_epoch TEXT NOT NULL CHECK(${U('origin_epoch')}),client_message_id TEXT NOT NULL CHECK(${U('client_message_id')}),source_protocol TEXT NOT NULL CHECK(typeof(source_protocol)='text' AND source_protocol IN ('a2a-msg.im.v1','a2a-msg.im.v2')),fingerprint TEXT NOT NULL CHECK(${H('fingerprint')}),payload_json TEXT CHECK(payload_json IS NULL OR (${J('payload_json',16777216)})),acceptance_state TEXT NOT NULL CHECK(typeof(acceptance_state)='text' AND acceptance_state IN ('pending','accepted')),reconciliation_state TEXT NOT NULL CHECK(typeof(reconciliation_state)='text' AND reconciliation_state IN ('none','required','remote_unknown')),message_id TEXT CHECK(message_id IS NULL OR (${U('message_id')})),accepted_at INTEGER CHECK(accepted_at IS NULL OR (${N('accepted_at')})),created_at INTEGER NOT NULL CHECK(${N('created_at')}),PRIMARY KEY(partition_id,origin_epoch,client_message_id),CHECK((acceptance_state='pending' AND message_id IS NULL AND accepted_at IS NULL) OR (acceptance_state='accepted' AND message_id IS NOT NULL AND accepted_at IS NOT NULL)))`,
  im_v2_client_received: `CREATE TABLE im_v2_client_received (partition_id TEXT NOT NULL CHECK(${H('partition_id')}),stream_epoch TEXT NOT NULL CHECK(${U('stream_epoch')}),seq INTEGER NOT NULL CHECK(${N('seq',1)}),message_id TEXT NOT NULL CHECK(${U('message_id')}),kind TEXT NOT NULL CHECK(typeof(kind)='text' AND kind IN ('message','content_expired')),fact_json TEXT NOT NULL CHECK(${J('fact_json',262144)}),fact_hash TEXT NOT NULL CHECK(${H('fact_hash')}),attachment_receipt_json TEXT CHECK(attachment_receipt_json IS NULL OR (${J('attachment_receipt_json',4096)})),recorded_at INTEGER NOT NULL CHECK(${N('recorded_at')}),server_confirmed INTEGER NOT NULL DEFAULT 0 CHECK(${B('server_confirmed')}),PRIMARY KEY(partition_id,stream_epoch,seq,kind),UNIQUE(partition_id,stream_epoch,message_id,kind),FOREIGN KEY(partition_id,stream_epoch) REFERENCES im_v2_client_receiver(partition_id,stream_epoch),CHECK(kind='message' OR attachment_receipt_json IS NULL))`,
  im_v2_client_receiver: `CREATE TABLE im_v2_client_receiver (partition_id TEXT NOT NULL CHECK(${H('partition_id')}) REFERENCES im_v2_client_partitions(partition_id),stream_epoch TEXT NOT NULL CHECK(${U('stream_epoch')}),handled_cursor INTEGER NOT NULL DEFAULT 0 CHECK(${N('handled_cursor')}),acked_cursor INTEGER NOT NULL DEFAULT 0 CHECK(${N('acked_cursor')}),server_handled INTEGER NOT NULL DEFAULT 0 CHECK(${N('server_handled')}),server_acked INTEGER NOT NULL DEFAULT 0 CHECK(${N('server_acked')}),instance_id TEXT CHECK(instance_id IS NULL OR (${U('instance_id')})),generation INTEGER CHECK(generation IS NULL OR (${N('generation',1)})),expires_at INTEGER CHECK(expires_at IS NULL OR (${N('expires_at')})),PRIMARY KEY(partition_id,stream_epoch),CHECK(acked_cursor<=handled_cursor),CHECK((instance_id IS NULL AND generation IS NULL AND expires_at IS NULL) OR (instance_id IS NOT NULL AND generation IS NOT NULL AND expires_at IS NOT NULL)))`,
  im_v2_client_batches: `CREATE TABLE im_v2_client_batches (batch_id TEXT NOT NULL PRIMARY KEY CHECK(${H('batch_id')}),partition_id TEXT NOT NULL CHECK(${H('partition_id')}),stream_epoch TEXT NOT NULL CHECK(${U('stream_epoch')}),kind TEXT NOT NULL CHECK(typeof(kind)='text' AND kind IN ('ack','expiry')),items_json TEXT NOT NULL CHECK(${J('items_json',16384)}),items_hash TEXT NOT NULL CHECK(${H('items_hash')}),state TEXT NOT NULL CHECK(typeof(state)='text' AND state IN ('pending','confirmed')),created_at INTEGER NOT NULL CHECK(${N('created_at')}),confirmed_at INTEGER CHECK(confirmed_at IS NULL OR (${N('confirmed_at')})),last_response_json TEXT CHECK(last_response_json IS NULL OR (${J('last_response_json',4096)})),FOREIGN KEY(partition_id,stream_epoch) REFERENCES im_v2_client_receiver(partition_id,stream_epoch),CHECK((state='pending' AND confirmed_at IS NULL) OR (state='confirmed' AND confirmed_at IS NOT NULL)))`,
  im_v2_client_one_active: `CREATE UNIQUE INDEX im_v2_client_one_active ON im_v2_client_partitions(center_origin,agent_id) WHERE status='active'`,
  im_v2_client_outgoing_pending: `CREATE INDEX im_v2_client_outgoing_pending ON im_v2_client_outgoing(partition_id,reconciliation_state,acceptance_state,created_at,origin_epoch,client_message_id)`,
  im_v2_client_received_pending: `CREATE INDEX im_v2_client_received_pending ON im_v2_client_received(partition_id,stream_epoch,server_confirmed,seq,kind)`,
  im_v2_client_batches_pending: `CREATE INDEX im_v2_client_batches_pending ON im_v2_client_batches(partition_id,state,created_at,batch_id)`,
});
export const JOURNAL_CHECKSUM = createHash('sha256').update(JSON.stringify(JOURNAL_DDL)).digest('hex');
